dist: xenial
language: node_js
node_js: "12"
sudo: required

matrix:
  fast_finish: true
  include:
    # JS Build
    - env: TEST=JS 

    # Python 3.7 Linux build
    - python: "3.7"
      language: python
      env: TEST=PYTHON
      cache: pip

    # Python 3.7 Mac build
    - env: TEST=PYTHON
      cache: pip
      os: osx
      osx_image: xcode11.2

  allow_failures:
    # Mac builds get extensively tested by the core developers.
    # They are also extremely slow to load on travis.
    # So pull requests should check these, but they are allowed
    # to fail

    # Python 3.7 Mac build
    - env: TEST=PYTHON
      cache: pip
      os: osx
      osx_image: xcode11.2

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
  homebrew:
    update: true
    packages:
      - python
      - python2
      - pybind11
      - cmake

before_install:
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then npm install -g yarn; fi

install:
  - node --version
  - yarn

script:
  - if [ "$TEST" = "JS" ]; then yarn lint && yarn test; fi
